### ISSUE TITLE
Support AWS provider 4.x

### ISSUE THREAD

**Issue by randomf** [infrablocks/terraform-aws-ecs-service#28]
Currently the `hashicorp/aws` version is pinned to version 3.X:
```
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.29"
    }
  }
```
Branch 4.X, introduced in February 2022, is incompatible with this module.

**Comment by Gryff** [comment]
Hi @randomf, this is on our roadmap for all of our terraform modules. We'll prioritise this one first 🙂

**Comment by jeroenhabets** [comment]
Hi @Gryff, seems like @tobyclemson 's commit d501fe443b4dc649c5c4f11bc88a35525af09ce1 resolved @randomf 's  issue so this could be Resolved/Closed. Cheers.
