### ISSUE TITLE
Host Path on Service Volume in Task Definition is non optional

### ISSUE THREAD

**Issue by alexparlett** [infrablocks/terraform-aws-ecs-service#4]
aws_lambda_function spec puts host_path as optional, the implementation in the task_definition.tf does not honour that.

https://github.com/infrablocks/terraform-aws-ecs-service/blob/master/task_definition.tf#L26

**Comment by tobyclemson** [comment]
Hey Alex,

I need a little more context. You refer to `aws_lambda_function` but that's not used in this module. Do you mean the `aws_ecs_task_definition` resource? Would you mind sharing the error you're getting?

In terms of making `host_path` optional, we could probably `coalesce` to an empty string. Not sure how strict terraform is these days when you refer to a map property that doesn't exist so don't know if this will work...

Thanks,
Toby

**Comment by alexparlett** [comment]
Yep sorry toby, aws_ecs_task_definition.

`Error: Missing map element

  on .terraform/modules/kafka_service/terraform-aws-ecs-service-2.0.0/task_definition.tf line 26, in resource "aws_ecs_task_definition" "service":
  26:       host_path = volume.value.host_path
    |----------------
    | volume.value is map of string with 1 element

This map does not have an element with the key "host_path".`

I've got a pr i'll raise against this in a sec.
